sparta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include("user.urls")),
]

user/urls.py
from django.urls import path, include
from user import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('home/', views.home, name="home"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    phone = models.CharField(max_length=256, blank=True)
    address = models.CharField(max_length=256)

user/views.py
from http.client import HTTPResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import User
from django.contrib import auth
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login as loginsession

# Create your views here.


def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        phone = request.POST.get('phone')
        address = request.POST.get('address')

        if password == password:
            Usermodel.objects.create_user(username = username, password = password, phone = phone, address = address)
            return redirect('/login')

def login(request):
    if request.method == 'GET':
        user = request.user.is_authenticated
        if user:
            return redirect('/home')
        else:
            return render(request, 'login.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        me = User.objects.get(username=username)
        if me.password == password:
            auth.login(request, me)
            request.session['user'] = me.username
            return redirect('/home')
        else:
            return render(request, 'login.html')

def home(request):
    if request.method == "GET":
        return render(request, "home.html")
    else:
        return redirect('/login')

user/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>django</title>
</head>
<body>
  django sparta 프로젝트의 메인 페이지입니다!
</body>
</html>

user/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Login</title>
</head>
<body>
  <h2>Log In</h2>
  <form action="{% url 'user:login' %}" method="post">
  {% csrf_token %}
  <input type="text" name="username">아이디</input></br>
  <input type="text" name="password">비밀번호</input></br>
  <button type="submit">로그인</button>
  <button type="button" onclick="location.href='/signup/'">회원가입</button>
  </form>
</body>
</html>

user/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Login</title>
</head>
<body>
  django sparta 프로젝트의 메인 페이지입니다!
  <h2>Log In</h2>
  <form action = "{% url 'user:signup' %}"method="post">
  {% csrf_token %}
  <input type="text" name="username">아이디</input></br>
  <input type="text" name="password">비밀번호</input></br>
  <input type="text" name="passwordcheck">비밀번호2</input></br>
  <input type="text" name="phone">핸드폰번호</input></br>
  <input type="text" name="address">주소</input></br>
  <button type="submit">회원가입</button>
  </form>
</body>
</html>